# Generated by Django 5.1.1 on 2024-09-19 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('internal_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Внутренний айди заявки')),
                ('city', models.CharField(choices=[('Казань', 'Казань'), ('Набережные Челны', 'Набережные Челны'), ('Нижнекамск', 'Нижнекамск'), ('Альметьевск', 'Альметьевск'), ('Зеленодольск', 'Зеленодольск')], max_length=255, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('customer', models.CharField(max_length=255, verbose_name='Клиент')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('package_type', models.CharField(choices=[('Письмо', 'Письмо'), ('Бандероль', 'Бандероль'), ('Габаритный груз', 'Габаритный груз')], max_length=255, verbose_name='Тип посылки')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Расстояние до склада')),
                ('load_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255, verbose_name='Cтатус заявки')),
                ('load_date', models.DateTimeField(verbose_name='Дата обновления статуса заявки')),
                ('internal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.deliveryrequest', verbose_name='Внутренний айди заявки')),
            ],
            options={
                'verbose_name': 'История статуса заявки',
                'verbose_name_plural': 'История статусов заявок',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('New', 'New'), ('Done', 'Done'), ('Canceled', 'Canceled'), ('Handed to courier', 'Handed to courier'), ('In progress', 'In progress')], max_length=255, verbose_name='Текущий статус заявки')),
                ('load_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления статуса заявки')),
                ('internal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.deliveryrequest', verbose_name='Внутренний айди заявки')),
            ],
            options={
                'verbose_name': 'Текущий статус заявки',
                'verbose_name_plural': 'Текущие статусы заявок',
            },
        ),
    ]
